# Generated by Django 5.0.3 on 2025-07-17 08:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_code', models.CharField(max_length=50, unique=True, verbose_name='BOM 코드')),
                ('name', models.CharField(max_length=200, verbose_name='BOM명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='버전')),
                ('revision_date', models.DateField(blank=True, null=True, verbose_name='개정일')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('pending', '검토대기'), ('approved', '승인'), ('active', '활성'), ('inactive', '비활성')], default='draft', max_length=20, verbose_name='상태')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 BOM')),
                ('production_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='생산 수량')),
                ('unit_of_measure', models.CharField(default='ea', max_length=10, verbose_name='단위')),
                ('setup_time_minutes', models.PositiveIntegerField(default=0, verbose_name='준비시간(분)')),
                ('production_time_minutes', models.PositiveIntegerField(default=0, verbose_name='생산시간(분)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boms', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='items.item', verbose_name='완성품')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_boms', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOM',
                'ordering': ['-created_at'],
                'unique_together': {('parent_item', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BOMChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('create', '신규 생성'), ('update', '수정'), ('delete', '삭제'), ('approve', '승인'), ('activate', '활성화'), ('deactivate', '비활성화')], max_length=20, verbose_name='변경 유형')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='이전 값')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='새 값')),
                ('change_reason', models.TextField(blank=True, verbose_name='변경 사유')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='bom.bom', verbose_name='BOM')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
            ],
            options={
                'verbose_name': 'BOM 변경 이력',
                'verbose_name_plural': 'BOM 변경 이력',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(choices=[('structure', '구조 검증'), ('cost', '비용 검증'), ('availability', '가용성 검증'), ('compliance', '규정 준수 검증')], max_length=20, verbose_name='검증 유형')),
                ('result', models.CharField(choices=[('pass', '통과'), ('fail', '실패'), ('warning', '경고')], max_length=10, verbose_name='결과')),
                ('message', models.TextField(verbose_name='메시지')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='상세 정보')),
                ('validated_at', models.DateTimeField(auto_now_add=True, verbose_name='검증일시')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='bom.bom', verbose_name='BOM')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='검증자')),
            ],
            options={
                'verbose_name': 'BOM 검증',
                'verbose_name_plural': 'BOM 검증',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('material', '원자재'), ('component', '부품'), ('subassembly', '반제품'), ('tool', '공구'), ('consumable', '소모품')], default='material', max_length=20, verbose_name='구성품 유형')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='소요량')),
                ('unit_of_measure', models.CharField(max_length=10, verbose_name='단위')),
                ('reference_designator', models.CharField(blank=True, max_length=50, verbose_name='참조 지시자')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('is_optional', models.BooleanField(default=False, verbose_name='선택사항')),
                ('is_phantom', models.BooleanField(default=False, verbose_name='팬텀 부품')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='유효 시작일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='유효 종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bom.bom', verbose_name='BOM')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='구성 아이템')),
                ('substitute_items', models.ManyToManyField(blank=True, related_name='substitute_for', to='items.item', verbose_name='대체 아이템')),
            ],
            options={
                'verbose_name': 'BOM 구성품',
                'verbose_name_plural': 'BOM 구성품',
                'ordering': ['sequence', 'item__name'],
                'unique_together': {('bom', 'item')},
            },
        ),
    ]
